### ISSUE TITLE
Bug w/ new deployment command

### ISSUE THREAD

**Issue by fdiebel** [EMRL/stir#100]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
New `bundle` command not being found

## If a bug:

| Q   | A
| --- | ---
| Deploy version | 3.6.4

### Steps to reproduce:
1. Type `deploy --verbose rymh`
2. Profit
 
### Log errors: 

```

10:06:57 Launching deployment from /var/www/html/rymh
Deploy to live server? [Y/n]
grep: /var/www/html/rymh/config/deploy.rb: No such file or directory
grep: /var/www/html/rymh/config/deploy.rb: No such file or directory
10:06:59 Testing connection for @
Connection for @ not established, an unknown error occurred.
Retry bundle exec mina deploy -f Minafile in verbose mode? [Y/n]
bundler: failed to load command: mina (/usr/local/bin/mina)
Bundler::GitError: git@bitbucket.org:emrl/mina-emrl.git (at master@a051331) is not yet checked out. Run `bundle install` first.
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/source/git.rb:204:in `rescue in load_spec_files'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/source/git.rb:201:in `load_spec_files'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/source/path.rb:97:in `local_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/source/git.rb:166:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/lazy_specification.rb:75:in `__materialize__'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:84:in `block in materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:81:in `map!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:81:in `materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/definition.rb:159:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/definition.rb:218:in `specs_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/definition.rb:207:in `requested_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:109:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:21:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler.rb:101:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/setup.rb:19:in `<top (required)>'
  /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
10:07:11 Testing deployment command: bundle exec mina deploy -f Minafile
Deployment exited due to a configuration problem (Error 1)
10:07:12 TRUE
10:07:12 OK
Exiting.
```

**Comment by joehorning** [comment]
was this behavior unique to rymh only?
